---
- name: install MariaDB
  apt:
    name: mariadb-server
    state: latest

- name: install some packages
  apt:
    name:
      - default-libmysqlclient-dev
      - build-essential
    state: present

- name: install PyMySQL
  pip:
    name: pymysql
    state: present

# Databases
#- name: create database
#  mariadb_databases: []
#    - name: nsapooldb
#      collation: utf8_general_ci
#      encoding: utf8

# Users
#- name: create database user
#  mariadb_users: []
#    - name: nsad04
#      password: E24h7U5kA9HJhq5VM98pm7p5zmJpf8AK
#      priv: "*.*:ALL"
#      state: present

- name: create database
  become_user: root
  become: yes
  community.mysql.mysql_db:
    name: SimpFunny
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock

- name: create database user
  become_user: root
  become: yes
  community.mysql.mysql_user:
    name: adminEcommerce
    password: motdepasse1
    priv: '*.*:ALL'
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    state: present

    #- name: >
    #    Import symfunny.sql,
    #    similar to mysql -u adminEcommerce -p motdepasse1 symfunny.sql
    #  community.mysql.mysql_db:
    #    state: import
    #    name: SimpFunny
    #    target: /var/www/app/symfunny.sql


# tasks file for MariaDBInstall
