<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZfw3qUO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZfw3qUO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZfw3qUO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZfw3qUO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZfw3qUO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zfw3qUO',
    'container.build_id' => '85f136d0',
    'container.build_time' => 1649164529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZfw3qUO');
